# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Make sure Python is installed
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install Python  # noqa no-changed-when
      ansible.builtin.raw: >
        if [ "" == "`which python3`" ];
        then echo "Python3 Not Found";
        if [ -n "`which apt-get`" ];
        then apt-get update -y && apt-get -y install python3;
        elif [ -n "`which yum`" ];
        then yum -y install python3 ;
        fi;
        fi
      args:
        executable: /bin/bash
...
